### ISSUE TITLE
Can't install it via panda install DBIish: Cannot invoke null object

### ISSUE THREAD

**Issue by wbiker** [tadzik/panda#165]
Hi,

I get following error when I try to install DBIish:

Cannot invoke null object
in sub strip-pod at lib/Panda/Builder.pm:15
in sub builder-order at lib/Panda/Builder.pm:56
in method build at lib/Panda/Builder.pm92
in method install at lib/Panda.pm:127
in method iresolve at lib/Panda.pm:214
in sub MAIN at panda:20
in block at panda:87

I guess I am missing a module, because installation works on my desktop but not on my fresh Fedora 22 installation.

Is what missing?
What is missing?

THX

**Comment by dwarring** [comment]
Seems to have started happening with recent rakudo builds. The current rakudo ac720edaf6b0abe40d4c8bc922e83a507f78e1b7 give me the same error with `panda install DBIsh`.

But a rakudo build from about a week ago works fine 27499bbdbf9bbc1163f9afb2397ce1af8c8493c4.

**Comment by dwarring** [comment]
I've golfed this a little and raised a rakudobug https://rt.perl.org/Ticket/Display.html?id=125342

**Comment by tadzik** [comment]
Good job @dwarring, much appreciated.
Meanwhile we can try looking for a workaround of some sort.

**Comment by flussence** [comment]
I was having the same problem with Linenoise, and I think I found a workaround in the meantime: installing other modules before the broken one in a single command (e.g. `panda install p6doc Linenoise`) seems to make it work.

**Comment by tadzik** [comment]
Wow, the fact that it worked sounds quite scary :o I'll try to get a solid look at it tomorrow.

**Comment by wbiker** [comment]
Hey, the workaround worked for me as well ^^ "panda install p6doc DBIish" ran wihtout errors, yeah.

**Comment by hoelzro** [comment]
@dwarring @tadzik I fixed the "Cannot invoke null object" bug a few days ago; please retry!

**Comment by dwarring** [comment]
DBIish now installs for me.

**Comment by wbiker** [comment]
I just now saw that it should be fixed.
To test whether it works now I did a
> rakudobrew self-upgrade
> rakudobrew build-panda
During the build-panda command the DBIish is successfully updated:
==> Successfully installed DBIish
Done, built panda for moar-nom
Updating shims
But following command failes:
[wolf@localhost ~]$ panda install DBIish
==> Fetching DBIish
==> Building DBIish
Cannot invoke null object
  in sub strip-pod at lib/Panda/Builder.pm:15
  in sub build-order at lib/Panda/Builder.pm:56
  in method build at lib/Panda/Builder.pm:92
  in method install at lib/Panda.pm:127
  in method resolve at lib/Panda.pm:214
  in sub MAIN at /home/wolf/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:20
  in block <unit> at /home/wolf/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:87

**Comment by tadzik** [comment]
The code causing that is now gone from panda, so the issue doesn't exist anymore. Please reopen if for some reason it still doesn't work :)

**Comment by wbiker** [comment]
Hmm, thx tadzik
I just updated rakudobrew here and tried to update panda. Unfortunately, it still fails:

rakudobrew build-panda
Cloning into 'panda'...
remote: Counting objects: 4226, done.
remote: Compressing objects: 100% (164/164), done.
remote: Total 4226 (delta 78), reused 0 (delta 0), pack-reused 4046
Receiving objects: 100% (4226/4226), 717.94 KiB | 1.25 MiB/s, done.
Resolving deltas: 100% (1879/1879), done.
Checking connectivity... done.
No need to rebootstrap, running normal bootstrap
==> Bootstrapping Panda
==> Installing panda from a local directory '/home/wolf/.rakudobrew/moar-nom/panda'
Could not download module metadata: Too many positionals passed; expected 1 argument but got 2
  in method update at /home/wolf/.rakudobrew/moar-nom/panda/lib/Panda/Ecosystem.pm:110
  in method init-projects at /home/wolf/.rakudobrew/moar-nom/panda/lib/Panda/Ecosystem.pm:48
  in method get-project at /home/wolf/.rakudobrew/moar-nom/panda/lib/Panda/Ecosystem.pm:119
  in method get-deps at /home/wolf/.rakudobrew/moar-nom/panda/lib/Panda.pm:166
  in method resolve at /home/wolf/.rakudobrew/moar-nom/panda/lib/Panda.pm:209
  in sub MAIN at bin/panda:18
  in block <unit> at bin/panda:95

==> Please make sure that /home/wolf/.rakudobrew/moar-nom/install/share/perl6/site/bin is in your PATH
Done, built panda for moar-nom

Anything I can do?

**Comment by tadzik** [comment]
Wow, that's very weird. Looking at it now...

**Comment by tadzik** [comment]
This really shouldn't be happening: bootstrap isn't even supposed to access the network at all.

Can I ask you to clear/move your ```~/.rakudobrew/moar-nom/install/share/perl6/site``` so that it's empty and try again? It seems to me that for some reason your bootstrap.pl loaded some old Panda installation that's lying around.

**Comment by wbiker** [comment]
I removed .rakudobrew at all and checked it out again. Now it is working. Obviously, the old installation was in a mess. 
Thanks for your help anyway!

**Comment by tadzik** [comment]
You're welcome, I'm glad all is fine after all :)
